### Introduction to NumPy

* Fast Mathematical Computational Library
* General purpose library using list available in Python is slow
* Homogenous data structure
* Specialized for doing mathematical computation
* Internally implemented using C - so fast
* High dimensional Computation
* Inbuilt utilities
* Mutabale

#### NumPy Creation
* From list
* zero init
* one init
* default value initialized
* range
* random

In [1]:
import numpy as np

#### From list

In [2]:
a = np.array([2,3,4,4,5,1])

In [3]:
a

array([2, 3, 4, 4, 5, 1])

In [4]:
a = np.array([2,3,4,4,5,1], dtype=np.float16)

In [5]:
a.dtype

dtype('float16')

In [6]:
a

array([ 2.,  3.,  4.,  4.,  5.,  1.], dtype=float16)

In [7]:
b = np.array(['hello','world','friends'])

* The size of each element is decided by maximum size of word. 7 in this case

In [8]:
b.dtype

dtype('<U7')

#### Zero & One init

In [10]:
z = np.zeros((4,4))

In [11]:
z

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [12]:
a

array([ 2.,  3.,  4.,  4.,  5.,  1.], dtype=float16)

##### zero_like
* create new data structure of same dimension/size as passed

In [13]:
np.zeros_like(a)

array([ 0.,  0.,  0.,  0.,  0.,  0.], dtype=float16)

##### ones

In [20]:
a = np.ones((3,3,3))

##### ones_like

In [21]:
np.ones_like(a)

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

#### full
* Init all the contents with this

In [22]:
np.full( (6,6), 99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [23]:
np.full((3,3), 'hello')

array([['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello']],
      dtype='<U5')

In [26]:
np.full_like(a, 10)

array([[[ 10.,  10.,  10.],
        [ 10.,  10.,  10.],
        [ 10.,  10.,  10.]],

       [[ 10.,  10.,  10.],
        [ 10.,  10.,  10.],
        [ 10.,  10.,  10.]],

       [[ 10.,  10.,  10.],
        [ 10.,  10.,  10.],
        [ 10.,  10.,  10.]]])

#### range
* Init a numpy array from start point to end point
* params - starting-point, ending-point & step size

In [24]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [25]:
np.arange(15,10,-1)

array([15, 14, 13, 12, 11])

#### random

In [40]:
d = np.random.rand(10)

In [41]:
d

array([ 0.62888571,  0.85219881,  0.20154966,  0.73766751,  0.52937559,
        0.9429892 ,  0.81017228,  0.72763046,  0.13116098,  0.17911883])

In [32]:
np.random.randn(2,3)

array([[ 0.33465919,  0.88021907,  0.22267529],
       [-0.5661579 , -0.87832113, -0.40185076]])

* int array between 5 & 10

In [37]:
np.random.randint(5,10,size=(3,3))

array([[7, 7, 9],
       [8, 9, 7],
       [9, 7, 7]])

##### shuffle
* randomizes the contents

In [42]:
np.random.shuffle(d)

In [43]:
d

array([ 0.17911883,  0.81017228,  0.72763046,  0.62888571,  0.52937559,
        0.13116098,  0.20154966,  0.9429892 ,  0.85219881,  0.73766751])

##### seed
* controls the output 
* using same seed, we will get same output

In [49]:
np.random.seed(1)
np.random.randint(5,10,size=(3,3))

array([[8, 9, 5],
       [6, 8, 5],
       [5, 6, 9]])

### Accessing elements

In [60]:
np.random.seed(10)
data = np.random.randint(2,20,size=(5,5))

In [61]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### Two ways to access this

In [52]:
data[2][1]

15

In [53]:
data[2,1]

15

#### Accessing only the first row

In [54]:
data[1]

array([12, 16,  6, 11, 19])

#### Accessing first onwards all the rows

In [55]:
data[1:]

array([[12, 16,  6, 11, 19],
       [ 2, 15, 11, 11,  9],
       [ 3,  2, 19, 10, 15],
       [17, 12, 10,  9,  5]])

#### Accessing till row 2

In [56]:
data[:2]

array([[ 9, 15,  8,  7, 13],
       [12, 16,  6, 11, 19]])

#### Column access

In [59]:
data[:,1:3]

array([[15,  8],
       [16,  6],
       [15, 11],
       [ 2, 19],
       [12, 10]])

* Question : Get slice containing 6,18,13,3

In [66]:
data[2:4, 2:4]

array([[ 6, 18],
       [13,  3]])

#### Shape, Size & Dimension
* These are not functions but attributes

Provide information on dimension

In [67]:
data.shape

(5, 5)

Total size of data

In [68]:
data.size

25

ndim - returns num of dimension, 2 in matrix, 3 in 

In [69]:
data.ndim

2

#### Reshaping data
* Changes shape & dimension of data but not size

In [71]:
a = np.array([1,2,3,4,5,6])

In [72]:
a.shape

(6,)

In [73]:
a.ndim

1

In [75]:
b = a.reshape((2,3))

In [76]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
b.ndim

2

In [78]:
b.shape

(2, 3)

In [80]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [82]:
b.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Adding one dim

In [84]:
a = np.array([1,2,3,4,5,6])

#### Adds one dimension 

In [87]:
a.reshape((a.shape[0],1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [88]:
a.shape

(6,)

#### Yet another way to add one more dimension 

In [89]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [94]:
data[:,np.newaxis]

array([[[11,  6, 17,  2, 19]],

       [[18, 19, 10, 11,  2]],

       [[12, 10,  6, 18,  6]],

       [[17, 13, 13,  3, 10]],

       [[ 6, 16, 19, 15,  7]]])

#### Convert data into 1-d of 25 elements

In [100]:
data.reshape(25)

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7])

In [99]:
data.reshape(*data.shape,1).shape

(5, 5, 1)

#### removal of dimension , converts into 1D data .i.e flattens it out

In [102]:
np.ravel(data)

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7])

### Concatination
* Combining data

#### Combining 1-D data

In [103]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [104]:
np.concatenate([x,y,x])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

#### Axis
* 0 - vertical
* 1 - horizontal

#### Combining 2D data
* by default axis zero

In [106]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [107]:

np.concatenate([data,data])

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [108]:
np.concatenate([data,data], axis=1)

array([[11,  6, 17,  2, 19, 11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2, 18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6, 12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10, 17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7,  6, 16, 19, 15,  7]])

#### append
* adds value at the end of the array

In [109]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [112]:
np.append(data, [1,2,3,4,5])

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7,  1,  2,  3,  4,  5])

In [114]:
np.append(data, [[1,2,3,4,5]], axis=0)

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [ 1,  2,  3,  4,  5]])

In [119]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

### horizontal stacking

In [120]:
np.hstack([data,data])

array([[11,  6, 17,  2, 19, 11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2, 18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6, 12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10, 17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7,  6, 16, 19, 15,  7]])

### vertical stacking

In [121]:
np.vstack([data,data])

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### Rules
* hstacking - num of rowst should be same 
* vstacking - num of cols should be same